<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1385043541621" stop="1385043541686">
    <title>Test with steps</title>
    <description>Testsuite has testcases with many steps
    and
many lines in description</description>
    <classname>my.company.TestWithSteps</classname>
    <test-cases start="1385043541658" stop="1385043541675" status="broken" severity="blocker">
        <title>Lot of steps test</title>
        <description>I have many steps 

    Parent Step 
    Last 
    MakeThisTestBroken</description>
        <failure>
            <message>No file found.</message>
            <stack-trace>java.io.FileNotFoundException: No file found.
	at my.company.steps.CommonSteps.makeThisTestBroken(CommonSteps.java:29)
	at my.company.TestWithSteps.lotOfStepsTest(TestWithSteps.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
</stack-trace>
        </failure>
        <steps start="1385043541671" stop="1385043541672" status="passed">
            <title>Parent step</title>
            <steps start="1385043541672" stop="1385043541672" status="passed">
                <title>&quot;First nested&quot; step</title>
            </steps>
            <steps start="1385043541672" stop="1385043541672" status="passed">
                <title>&quot;Second nested&quot; step</title>
            </steps>
            <steps start="1385043541672" stop="1385043541672" status="passed">
                <title>&quot;Third nested&quot; step</title>
            </steps>
        </steps>
        <steps start="1385043541672" stop="1385043541672" status="passed">
            <title>&quot;Last&quot; step</title>
        </steps>
        <steps start="1385043541672" stop="1385043541673" status="broken">
            <title>Make this test broken</title>
        </steps>
    </test-cases>
    <test-cases start="1385043541658" stop="1385043541686" status="failed" severity="critical">
        <title>Attachments test</title>
        <description>Single-line description</description>
        <failure>
            <message>This test should be failed</message>
            <stack-trace>java.lang.AssertionError: This test should be failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at my.company.steps.CommonSteps.makeThisTestFailed(CommonSteps.java:35)
	at my.company.TestWithSteps.attachmentsTest(TestWithSteps.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
</stack-trace>
        </failure>
        <steps start="1385043541685" stop="1385043541686" status="failed">
            <title>Make this test failed</title>
            <attachments title="TXT Attachment" source="7da7b2ac-a413-4abe-877b-a41efa870870-attachment.txt" type="txt"/>
        </steps>
        <attachments title="JSON Attachment" source="5860c82a-d3e8-47bb-8766-7dbc706c74c3-attachment.json" type="json"/>
        <attachments title="XML Attachment" source="b8483cb7-fdde-4971-9080-66c97525ebea-attachment.xml" type="xml"/>
        <attachments title="JPG Attachment" source="647ed301-648f-4ec6-b514-c18e9db4b7ac-attachment.jpg" type="jpg"/>
    </test-cases>
</ns2:test-suite>
