<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1386060870506" stop="1386060870559">
    <title>Test With Steps</title>
    <description>Testsuite has testcases with many steps
    and
many lines in description</description>
    <classname>my.company.TestWithSteps</classname>
    <test-cases start="1386060870521" stop="1386060870534" status="broken" severity="blocker">
        <title>lot Of Steps Test</title>
        <description>I have many steps 

    Parent Step 
    Last 
    MakeThisTestBroken</description>
        <failure>
            <message>No file found.</message>
            <stack-trace>java.io.FileNotFoundException: No file found.
	at my.company.steps.CommonSteps.makeThisTestBroken(CommonSteps.java:29)
	at my.company.TestWithSteps.lotOfStepsTest(TestWithSteps.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
</stack-trace>
        </failure>
        <steps start="1386060870532" stop="1386060870533" status="passed">
            <title>Parent step</title>
            <steps start="1386060870533" stop="1386060870533" status="passed">
                <title>&quot;First nested&quot; step</title>
            </steps>
            <steps start="1386060870533" stop="1386060870533" status="passed">
                <title>&quot;Second nested&quot; step</title>
            </steps>
            <steps start="1386060870533" stop="1386060870533" status="passed">
                <title>&quot;Third nested&quot; step</title>
            </steps>
        </steps>
        <steps start="1386060870533" stop="1386060870533" status="passed">
            <title>&quot;Last&quot; step</title>
        </steps>
        <steps start="1386060870534" stop="1386060870534" status="broken">
            <title>Make this test broken</title>
        </steps>
    </test-cases>
    <test-cases start="1386060870522" stop="1386060870559" status="failed" severity="critical">
        <title>attachments Test</title>
        <description>Single-line description</description>
        <failure>
            <message>This test should be failed</message>
            <stack-trace>java.lang.AssertionError: This test should be failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at my.company.steps.CommonSteps.makeThisTestFailed(CommonSteps.java:35)
	at my.company.TestWithSteps.attachmentsTest(TestWithSteps.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
</stack-trace>
        </failure>
        <steps start="1386060870558" stop="1386060870559" status="failed">
            <title>Make this test failed</title>
            <attachments title="TXT Attachment" source="e15a3e6c-0bc4-46d6-a5ff-d45a90d344ff-attachment.txt" type="txt"/>
        </steps>
        <attachments title="JSON Attachment" source="6495bcbb-d618-47a0-b9e2-22a86276c94d-attachment.json" type="json"/>
        <attachments title="XML Attachment" source="6cd13696-1c37-4850-b961-48d11a8bd478-attachment.xml" type="xml"/>
        <attachments title="JPG Attachment" source="78c34d00-fc25-4e78-b704-685999d6143d-attachment.jpg" type="jpg"/>
    </test-cases>
</ns2:test-suite>
